name: Launch

on:
    push:
        branches:
        - dev
        - main
        - master
    pull_request:
jobs:
    build:
        runs-on: ubuntu-20.04
        container: docker://epitechcontent/epitest-docker
        steps:
        - uses: actions/checkout@v2
        - name: Install Xvfb
          run: dnf install xorg-x11-server-Xvfb psmisc -y
        - name: Build
          shell: bash
          run: "make 2>&1 | tee build_output"
        - name: Run
          shell: bash
          run: |
            Xvfb :1 -screen 0 1024x768x24 &
            sh -c "sleep 20 && killall my_rpg" &
            export DISPLAY="1:0"
            bash -c './my_rpg; CODE=$?; if [[ $CODE == 143 ]]; then exit 0; else exit $CODE; fi'
